# owpost configuration file
# in TOML format https://toml.io/en/
#
# Normally resides in /etc/owlogger/owpost.toml
# used for owpost.py and generalpost.py
#
# See https://github.com/alfille/owlogger

# blank lines and text after '#' comments are ignored

# server location (external)
# usually a valid subdomain address
#server=owlogger.mypvs.net

# for testing if owlogger in running on same machine:
server="http://localhost:8001"

# owserver location (internal)
# Usually local and on well-known port
owserver="localhost:4304"

# name
# to distinguish multiple sources
# Choose a real, insightful name
name="owpost"

# Authentification token
# choose something better than this
token="simple_string"

# Temperature
# only one is needed and default is Fahrenheit
Fahenheit=true
# Celsius=true

# debugging output (for testing)
debug=false

# period
# better done in systemd or cron!
#period=15
